### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by dashed** [Dashed/providence#1]
- [ ] add test case for propagate
- [ ] split `propagate` to `propagateUp` and `propagateDown`
- [ ] be able to define stop points (e.g. using another cursor) when propagating up the tree.
- [ ] `cursor(key1, key2, ...)` sugar to `cursor([key1, key2, ...])`
- [ ] update `README` to include `reduce` and `forEach`
- [x] `Providence.prototype.root()`
- [ ] remove Immutable dependency
